name: YKS Sonuclari Kontrol Et

on:
  schedule:
    - cron: '*/6 * * * *'
  workflow_dispatch:

jobs:
  kontrol_isleri:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Kopyala
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

    - name: Kütüphaneleri Yükle ve Çalıştır
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install requests beautifulsoup4 twilio
        python3 -u yks.py
